version: "3.4"

services:
  clamav-server:
    ports:
      - "3310"
  virusscanner.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ClamAVServerHost=clamav-server
      - ClamAVServerPort=3310
    ports:
      - "80"
