version: '3.4'

services:
  clamav-server:
    image: mkodockx/docker-clamav
  minio:
    image: minio/minio
    volumes:
      - data:/data
    command: server /data
  mssql:
    image: microsoft/mssql-server-linux
  virusscanner.mvc:
    image: ${DOCKER_REGISTRY-}virusscanner
    build:
      context: .
      dockerfile: VirusScanner.MVC/Dockerfile
    depends_on:
      - clamav-server
      - minio
      - mssql
volumes:
  data:
