// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirusScanner.MVC.Persistence;

namespace VirusScanner.MVC.Persistence.Migrations
{
    [DbContext(typeof(UploadsDbContext))]
    [Migration("20190505201636_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VirusScanner.MVC.Domain.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("ContentType")
                        .HasMaxLength(100);

                    b.Property<bool>("Infected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(24);

                    b.Property<string>("ScanResult")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<DateTime>("Scanned")
                        .HasColumnType("datetime");

                    b.Property<long>("Size");

                    b.Property<DateTime>("Uploaded")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("VirusScanner.MVC.Domain.Entities.Virus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FileId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Viruses");
                });

            modelBuilder.Entity("VirusScanner.MVC.Domain.Entities.Virus", b =>
                {
                    b.HasOne("VirusScanner.MVC.Domain.Entities.File", "File")
                        .WithMany("Viruses")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
